[versions]
kotlin = "1.9.10"
springboot = "2.7.11"
spring-dependency-manager = "1.1.3"
ktor = "2.3.7"

[libraries]
springboot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
springboot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
springboot-configurationprocessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
springboot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure" }

ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-manager" }

[bundles]